### ISSUE TITLE
Try to download

### ISSUE THREAD

**Issue by Santoryu-Style** [Rokuazery/LoL-Assist#15]
Hi,

You guys might make fun of me but i have issues to install the program.
There is no tutorial or exe file.

Thank you!

**Comment by Rokuazery** [comment]
I'll link you to a video tutorial that I made since I'm bad at explaining stuff.
[Video](https://streamable.com/ynp228) | [LoL-Assist Releases Page](https://github.com/Rokuazery/LoL-Assist/releases)


**You're welcome! 😄**

**Comment by Santoryu-Style** [comment]
It's working, thank you so much!
