### ISSUE TITLE
Instant Close

### ISSUE THREAD

**Issue by DoisPontinhos** [Rokuazery/LoL-Assist#2]
So I start the program, open league and the moment league is done loading the program closes. Any ideas?
Btw would love to see a way for people to create their own builds and be able to import

**Comment by Rokuazery** [comment]
May I know what version did you use?

**Comment by DoisPontinhos** [comment]
I'm using the latest version 1.5.0.0

**Comment by DoisPontinhos** [comment]
13-Sep-21 2:29:09 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 2:29:09 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 2:29:11 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 2:29:11 PM [LoL Assist] >> Unable to connect to the remote server

The log file shows this

**Comment by Rokuazery** [comment]
Unfortunately, I can't replicate this issue I've tested using the NA, and the Garena version.
Perhaps, you can try restarting LoL Assist that may fix the issue you're having, or try running League first then run LoL Assist after.

The logs that you have sent me is normal, if LoL Assist does not find the process that it seeks for which is "LeagueClient", an exception will be made that results in triggering "Lockfile not found", you can try running LoL Assist as admin if you haven't tried it.

**Comment by DoisPontinhos** [comment]
I've tried running LOL Assist has admin, tried running after opening league, nothing seems to work. The moment league loads, lol assist just closes. I'm using the EUW version

**Comment by DoisPontinhos** [comment]
If league is closed the program opens normally but the moment I open league it closes

**Comment by DoisPontinhos** [comment]
13-Sep-21 3:38:57 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:57 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:57 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:57 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:57 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:57 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:38:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:05 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 3:39:06 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 3:39:49 PM [LoL Assist] >> Creating LoL Assist folder...
13-Sep-21 3:39:50 PM [LoL Assist] >> Initializing Dictionaries...
13-Sep-21 3:39:58 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 3:39:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:58 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 3:39:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:58 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:39:59 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:00 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:01 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:02 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:03 PM [LoL Assist] >> Lockfile not found.
13-Sep-21 3:40:05 PM [LoL Assist] >> Unable to connect to the remote server
13-Sep-21 3:40:05 PM [LoL Assist] >> Unable to connect to the remote server

**Comment by DoisPontinhos** [comment]
Any dependencies I need?

**Comment by Rokuazery** [comment]
Can you show me all the files inside the LoL Assist folder?

**Comment by DoisPontinhos** [comment]
![image](https://user-images.githubusercontent.com/82269167/133105144-00c44122-2e07-4049-843e-ab7686f3763f.png)

**Comment by Rokuazery** [comment]
I can't seem to find anything wrong with it, maybe try deleting the LoL Assist folder data, if that doesn't work either I am so sorry. I have no idea.

**Comment by DoisPontinhos** [comment]
Are there any dependencies I need? Like .net framework or something ?

**Comment by Rokuazery** [comment]
I don't know maybe you haven't installed .NET Framework 4.8 runtime?
if so you can download it here https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

**Comment by DoisPontinhos** [comment]
I have it, still trying to figure out what's the problem

**Comment by DoisPontinhos** [comment]
Updated all my drivers, restarted my pc and still no progress

**Comment by DoisPontinhos** [comment]
Tried the first release and the program didn't close after league loading but still saying "Connecting to League Client..."

![image](https://user-images.githubusercontent.com/82269167/133116784-58f7823f-170c-4812-a51f-84c34c244116.png)

**Comment by Rokuazery** [comment]
![image](https://user-images.githubusercontent.com/48817307/133122885-49a695db-bcab-4e95-98a5-56d3fcd01a11.png)
I am currently installing the EUW version to investigate this issue

**Comment by DoisPontinhos** [comment]
Thank You I really want to use this app

**Comment by Rokuazery** [comment]
A new update has been released you can now update through LoL Assist or download manually through Github.
