### ISSUE TITLE
No longer functional with 64 bit version of the client.

### ISSUE THREAD

**Issue by Smug-Kayle** [Rokuazery/LoL-Assist#21]
It was already buggy but now it doesn't even connect to the client.

**Comment by xerus6** [comment]
It's working fine for me.

**Comment by xerus6** [comment]
Same here.

**Comment by Smug-Kayle** [comment]
> Same here.
The project has not been updated in so long, maybe it's discontinued.

**Comment by Rokuazery** [comment]
It has been a while since I last updated this project, but I will do my best to fix the issues right now.

**Comment by xerus6** [comment]
> 

I appreciate that, thanks !
