### ISSUE TITLE
Hi, I have a problem

### ISSUE THREAD

**Issue by Klindson** [Rokuazery/LoL-Assist#23]
Every time I open the program, and import the rune, it closes by itself, I believe it is a bug, can anyone help me solve this?!

obs:  I have already reinstalled the program several times, and it didn't work.

**Comment by Rokuazery** [comment]
Unfortunately, I've already tried using both METASrc and U.GG in multiple games, but I'm still unable to reproduce the issue you're experiencing. To help you resolve this problem, please provide the version of the program you're using and the LoLA.log file. This log may contain information about the error that caused the program to close.

**Comment by Klindson** [comment]
See this 
![image](https://user-images.githubusercontent.com/11722973/236894513-708c907c-8bf2-4d74-9627-8ea374c71f8a.png)

**Comment by Rokuazery** [comment]
Releasing new version soon with bug fixes and OP.GG runes
