### ISSUE TITLE
not an issue it's just a suggestion <3

### ISSUE THREAD

**Issue by dunklamike** [Rokuazery/LoL-Assist#9]
let me start by saying i love this project so much and ty for creating it
here's my suggestion i think adding a **realtime** runes editor
let's say for example u pick a champ, auto imports runes and then u see that u have have a favorible matchup so u wanna change ur runes but instead of doing it in the client (i have a really laggy client on my low end pc by low end i mean 12years old pc) 
we can have an "**Edit**" button to open up a new window to quickly change ur runes
like taking demolish if u plan on playing aggressive or swap ur armor rune with magic resist if ur laner pick an ap champ
and for this im now using an app called "**Simple Rune Maker**" u can check it out to understand what i mean 
it's simple and straightforward and i really would love to have an option like this in ur app 
sorry i typed for this long hope i didnt bother u but anyway ty (and we need u.gg runes asap haha)
love u, have a great day

this is what the app looks like
![Screenshot_2](https://user-images.githubusercontent.com/108146963/175611769-6b53fecf-e2ed-4a33-8e92-66aa0b167405.png)

**Comment by Rokuazery** [comment]
Thank you for your suggestion. I've been working on your suggestion for a while now, and also thank you for the love and support 😄❤️
Here's some preview below:
![image](https://user-images.githubusercontent.com/48817307/177532793-38ecdc37-7457-4826-b7e3-24f785601def.png)
![image](https://user-images.githubusercontent.com/48817307/177532023-00ff4156-e45a-4dbd-b51c-5b215fbb58f9.png)
 I'll be releasing this update in the upcoming month or sooner, I'm also working on U.GG runes and still figuring out how to fetch data properly from the website.
